dist: xenial
sudo: required

language: java
install: true

before_install:
  - sudo -E ./script/travis_before_install.sh

cache:
  timeout: 604800  # 1 week
  apt: true
  directories:
    - ~/protobuf-3.6.1

jdk:
  - oraclejdk8

script:
  - ./gradlew build
