dist: trusty
sudo: required

language: java
install: true

before_install:
  - sudo -E ./src/buildscript/before_install.sh

cache:
  timeout: 604800  # 1 week
  apt: true
  directories:
    - ~/protobuf3

jdk:
  - oraclejdk8

script:
  - ./gradlew build
